### ISSUE TITLE
Write operations (Apply/Update) silently fail under concurrent load

### ISSUE THREAD

**Issue by toga4** [GoogleCloudPlatform/cloud-spanner-emulator#282]
## Description
Under concurrent load, write operations using both `Client.Apply()` (mutations) and `ReadWriteTransaction.Update()` (DML) **silently succeed but the data is never persisted**. The write operation returns successfully without errors, but subsequent reads cannot find the data. This is not a visibility/propagation delay issue - the write operation itself appears to be lost entirely, as re-attempting the same insert operation succeeds (which would fail with a duplicate key error if the first write had actually persisted).

## Environment
- **Emulator**: `gcr.io/cloud-spanner-emulator/emulator:1.5.42`
- **Client Library**: `cloud.google.com/go/spanner` (Go SDK)
- **Test Framework**: `github.com/testcontainers/testcontainers-go/modules/gcloud/spanner`
- **Go Version**: go1.25.3
- **Test Environments**:
  - Local: darwin/arm64, Apple M4 (10 physical cores, 10 logical cores)
  - GitHub Actions: `blacksmith-8vcpu-ubuntu-2404` runner
- **Test Parallelism**: Limited by `GOMAXPROCS` (default: number of CPU cores)

## Steps to Reproduce

I've created three test cases that demonstrate this issue:

### Test 1: `TestSpannerApplyFailure` - Apply with Mutation API
1. Creates 300 parallel test cases (actual parallelism limited by CPU cores)
2. Each test case creates a separate database
3. Inserts a row using `Client.Apply()` with mutation
4. Immediately attempts to read the same row using `Client.Single().ReadRow()`
5. Retries read up to 5 times with 10ms delay if the read fails

### Test 2: `TestSpannerUpdateFailure` - DML with ReadWriteTransaction
1. Same setup as Test 1
2. Inserts a row using DML `INSERT` statement within `ReadWriteTransaction`
3. Reads the row count with a `SELECT COUNT(*)` query
4. Demonstrates the issue affects DML operations, not just mutations

### Test 3: `TestSpannerApplyWithRetry` - Retry the write operation itself
1. Same setup as Test 1
2. **Retries the `Apply()` operation itself** (not just the read) up to 5 times
3. This test typically succeeds, proving that:
   - The first write operation is completely lost (not just delayed)
   - If the write was persisted, the retry would fail with a duplicate key error
   - Re-attempting the same insert succeeds, confirming data loss

<details>
<summary>Full test code (click to expand)</summary>

```go
package spanner_test

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"cloud.google.com/go/spanner"
	database "cloud.google.com/go/spanner/admin/database/apiv1"
	"cloud.google.com/go/spanner/admin/database/apiv1/databasepb"
	instance "cloud.google.com/go/spanner/admin/instance/apiv1"
	"cloud.google.com/go/spanner/admin/instance/apiv1/instancepb"
	tcspanner "github.com/testcontainers/testcontainers-go/modules/gcloud/spanner"
)

func TestMain(m *testing.M) {
	cleanup, err := setupSpannerEmulator(context.Background())
	if err != nil {
		panic(fmt.Sprintf("Failed to setup Spanner emulator: %v", err))
	}

	code := m.Run()

	cleanup()

	os.Exit(code)
}

func setupSpannerEmulator(ctx context.Context) (func(), error) {
	container, err := tcspanner.Run(ctx, "gcr.io/cloud-spanner-emulator/emulator:latest")
	if err != nil {
		return nil, fmt.Errorf("Failed to run Spanner emulator container: %w", err)
	}
	os.Setenv("SPANNER_EMULATOR_HOST", fmt.Sprintf("passthrough:///%s", container.URI()))

	instanceAdminClient, err := instance.NewInstanceAdminClient(ctx)
	if err != nil {
		return nil, fmt.Errorf("Failed to create Spanner instance admin client: %w", err)
	}
	defer instanceAdminClient.Close()

	op, err := instanceAdminClient.CreateInstance(ctx, &instancepb.CreateInstanceRequest{
		Parent:     "projects/test-project",
		InstanceId: "test-instance",
		Instance: &instancepb.Instance{
			Config:      "projects/test-project/instanceConfigs/emulator-config",
			DisplayName: "test-instance",
			NodeCount:   1,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to create Spanner instance: %w", err)
	}

	i, err := op.Wait(ctx)
	if err != nil {
		return nil, fmt.Errorf("Failed to wait for Spanner instance creation: %w", err)
	}

	if i.State != instancepb.Instance_READY {
		return nil, fmt.Errorf("Spanner instance is not ready: %v", i.State)
	}

	return func() {
		if err := container.Terminate(ctx); err != nil {
			panic(fmt.Sprintf("Failed to terminate Spanner emulator container: %v", err))
		}
	}, nil
}

func TestSpannerApplyFailure(t *testing.T) {
	t.Parallel()

	for i := range 300 {
		t.Run(fmt.Sprintf("Test %d", i), func(t *testing.T) {
			t.Parallel()

			ctx := t.Context()
			adminClient, err := database.NewDatabaseAdminClient(ctx)
			if err != nil {
				t.Fatalf("Failed to create Spanner database admin client: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.Close(); err != nil {
					t.Fatalf("Failed to close Spanner database admin client: %v", err)
				}
			})

			op, err := adminClient.CreateDatabase(ctx, &databasepb.CreateDatabaseRequest{
				Parent:          "projects/test-project/instances/test-instance",
				CreateStatement: fmt.Sprintf("CREATE DATABASE `apply-failure-%03d`", i),
				ExtraStatements: []string{
					"CREATE TABLE Test (ID INT64 NOT NULL, Name STRING(MAX) NOT NULL) PRIMARY KEY(ID)",
				},
			})
			if err != nil {
				t.Fatalf("Failed to create Spanner database: %v", err)
			}

			d, err := op.Wait(ctx)
			if err != nil {
				t.Fatalf("Failed to wait for Spanner database creation: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.DropDatabase(context.WithoutCancel(ctx), &databasepb.DropDatabaseRequest{
					Database: d.Name,
				}); err != nil {
					t.Fatalf("Failed to drop Spanner database: %v", err)
				}
			})

			client, err := spanner.NewClient(ctx, d.Name)
			if err != nil {
				t.Fatalf("Failed to create Spanner client: %v", err)
			}
			t.Cleanup(func() {
				client.Close()
			})

			if _, err := client.Apply(ctx, []*spanner.Mutation{
				spanner.Insert("Test", []string{"ID", "Name"}, []any{1, "test"}),
			}); err != nil {
				t.Fatalf("Failed to apply Spanner mutations: %v", err)
			}

			retried := 0
			for range 5 {
				if _, err := client.Single().ReadRow(ctx, "Test", spanner.Key{1}, []string{"ID", "Name"}); err != nil {
					t.Logf("Failed to read Spanner row at attempt %d: %v", retried+1, err)
					time.Sleep(10 * time.Millisecond)
					retried++
					continue
				}
				break
			}
			if retried > 0 {
				t.Errorf("Failed to read Spanner row %d times", retried)
			}
		})
	}
}

func TestSpannerUpdateFailure(t *testing.T) {
	t.Parallel()

	for i := range 300 {
		t.Run(fmt.Sprintf("Test %d", i), func(t *testing.T) {
			t.Parallel()

			ctx := t.Context()
			adminClient, err := database.NewDatabaseAdminClient(ctx)
			if err != nil {
				t.Fatalf("Failed to create Spanner database admin client: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.Close(); err != nil {
					t.Fatalf("Failed to close Spanner database admin client: %v", err)
				}
			})

			op, err := adminClient.CreateDatabase(ctx, &databasepb.CreateDatabaseRequest{
				Parent:          "projects/test-project/instances/test-instance",
				CreateStatement: fmt.Sprintf("CREATE DATABASE `update-failure-%03d`", i),
				ExtraStatements: []string{
					"CREATE TABLE Test (ID INT64 NOT NULL, Name STRING(MAX) NOT NULL) PRIMARY KEY(ID)",
				},
			})
			if err != nil {
				t.Fatalf("Failed to create Spanner database: %v", err)
			}

			d, err := op.Wait(ctx)
			if err != nil {
				t.Fatalf("Failed to wait for Spanner database creation: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.DropDatabase(context.WithoutCancel(ctx), &databasepb.DropDatabaseRequest{
					Database: d.Name,
				}); err != nil {
					t.Fatalf("Failed to drop Spanner database: %v", err)
				}
			})

			client, err := spanner.NewClient(ctx, d.Name)
			if err != nil {
				t.Fatalf("Failed to create Spanner client: %v", err)
			}
			t.Cleanup(func() {
				client.Close()
			})

			if _, err := client.ReadWriteTransaction(ctx, func(ctx context.Context, rwt *spanner.ReadWriteTransaction) error {
				if _, err := rwt.Update(ctx, spanner.NewStatement("INSERT INTO Test (ID, Name) VALUES (1, 'test')")); err != nil {
					return err
				}
				return nil
			}); err != nil {
				t.Fatalf("Failed to read Spanner row: %v", err)
			}

			retried := 0
			for range 5 {
				if err := client.Single().Query(ctx, spanner.NewStatement("SELECT COUNT(*) FROM Test WHERE ID = 1")).Do(func(r *spanner.Row) error {
					var count int64
					if err := r.Column(0, &count); err != nil {
						return err
					}
					if count != 1 {
						return fmt.Errorf("count is not 1: result(%d) != expected(1)", count)
					}
					return nil
				}); err != nil {
					t.Logf("Failed to read Spanner row at attempt %d: %v", retried+1, err)
					time.Sleep(10 * time.Millisecond)
					retried++
					continue
				}
				break
			}
			if retried > 0 {
				t.Errorf("Failed to read Spanner row %d times", retried)
			}
		})
	}
}

func TestSpannerApplyWithRetry(t *testing.T) {
	t.Parallel()

	for i := range 300 {
		t.Run(fmt.Sprintf("Test %d", i), func(t *testing.T) {
			t.Parallel()

			ctx := t.Context()
			adminClient, err := database.NewDatabaseAdminClient(ctx)
			if err != nil {
				t.Fatalf("Failed to create Spanner database admin client: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.Close(); err != nil {
					t.Fatalf("Failed to close Spanner database admin client: %v", err)
				}
			})

			op, err := adminClient.CreateDatabase(ctx, &databasepb.CreateDatabaseRequest{
				Parent:          "projects/test-project/instances/test-instance",
				CreateStatement: fmt.Sprintf("CREATE DATABASE `apply-with-retry-%03d`", i),
				ExtraStatements: []string{
					"CREATE TABLE Test (ID INT64 NOT NULL, Name STRING(MAX) NOT NULL) PRIMARY KEY(ID)",
				},
			})
			if err != nil {
				t.Fatalf("Failed to create Spanner database: %v", err)
			}

			d, err := op.Wait(ctx)
			if err != nil {
				t.Fatalf("Failed to wait for Spanner database creation: %v", err)
			}
			t.Cleanup(func() {
				if err := adminClient.DropDatabase(context.WithoutCancel(ctx), &databasepb.DropDatabaseRequest{
					Database: d.Name,
				}); err != nil {
					t.Fatalf("Failed to drop Spanner database: %v", err)
				}
			})

			client, err := spanner.NewClient(ctx, d.Name)
			if err != nil {
				t.Fatalf("Failed to create Spanner client: %v", err)
			}
			t.Cleanup(func() {
				client.Close()
			})

			result := false
			for i := range 5 {
				if _, err := client.Apply(ctx, []*spanner.Mutation{
					spanner.Insert("Test", []string{"ID", "Name"}, []any{1, "test"}),
				}); err != nil {
					t.Fatalf("Failed to apply Spanner mutations: %v", err)
				}

				if _, err := client.Single().ReadRow(ctx, "Test", spanner.Key{1}, []string{"ID", "Name"}); err != nil {
					t.Logf("Failed to read Spanner row at attempt %d: %v", i+1, err)
					continue
				}

				result = true
				break
			}
			if !result {
				t.Errorf("Failed to read Spanner row in 5 attempts")
			}
		})
	}
}
```

</details>

## Expected Behavior
After a write operation (`Client.Apply()` or `ReadWriteTransaction.Update()`) returns successfully, the data should be persisted and immediately visible to subsequent reads.

## Actual Behavior
Under concurrent load (300 parallel test cases, limited to ~10 actual concurrent executions by CPU cores), write operations silently fail:

1. **Write operation returns success** - No error is returned from `Apply()` or `Update()`
2. **Data is not persisted** - Subsequent reads fail with "row not found"
3. **Write operation is completely lost** - Retrying the same insert succeeds (proving the first write never happened)

### Evidence that writes are lost (not just delayed):

**Test 1 & 2 failures** (`TestSpannerApplyFailure`, `TestSpannerUpdateFailure`):
```
--- FAIL: TestSpannerApplyFailure/Test_123 (0.66s)
    spanner_test.go:131: Failed to read Spanner row at attempt 1: spanner: code = "NotFound", desc = "row not found(Table: Test, PrimaryKey: (1))"
    spanner_test.go:131: Failed to read Spanner row at attempt 2: spanner: code = "NotFound", desc = "row not found(Table: Test, PrimaryKey: (1))"
    spanner_test.go:131: Failed to read Spanner row at attempt 3: spanner: code = "NotFound", desc = "row not found(Table: Test, PrimaryKey: (1))"
    spanner_test.go:131: Failed to read Spanner row at attempt 4: spanner: code = "NotFound", desc = "row not found(Table: Test, PrimaryKey: (1))"
    spanner_test.go:131: Failed to read Spanner row at attempt 5: spanner: code = "NotFound", desc = "row not found(Table: Test, PrimaryKey: (1))"
    spanner_test.go:139: Failed to read Spanner row 5 times
```

**Test 3 success** (`TestSpannerApplyWithRetry`):
- When we retry the **write operation itself** (not just the read), the test passes
- The retry insert with the same primary key (ID=1) **succeeds** without a duplicate key error
- This proves the first insert was completely lost, not just delayed
- If the first insert had persisted, the second attempt would fail with "ALREADY_EXISTS" error

## Impact
This issue causes tests to be flaky when using the emulator under concurrent load.

## Additional Context
- Issue appears under moderate concurrency (300 test cases, ~10 concurrent due to CPU cores)
- Each test uses a completely separate database - no cross-contamination possible
- Confirmed to affect:
  - **Mutation API** (`Client.Apply()`)
  - **DML statements** (`ReadWriteTransaction.Update()`)
  - Other write operations may be affected as well
- This appears to be a race condition in the emulator's transaction/commit handling
- **Workaround**: Retry write operations and verify with a read (but this defeats the purpose of testing against an emulator)

**Comment by toga4** [comment]
## Update: Issue is related to multiplexed sessions

I've found that this issue only occurs when multiplexed sessions are enabled for read-write transactions.

### Workaround

Disabling multiplexed sessions resolves the issue:

```go
os.Setenv("GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW", "false")
```

With this setting, all tests pass consistently without any failures.

The issue appears to be specific to the emulator's multiplexed sessions implementation under concurrent load.

**Comment by sakthivelmanii** [comment]
Resolved in https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.50.

**Comment by apstndb** [comment]
@sakthivelmanii  
> Resolved in https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.50.

I’m not sure my case (https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/282#issuecomment-3659846637) has been fixed.

From what I can tell, this change appears to prevent transaction ID collisions when multiple databases are involved:  
https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/commit/690842a75a039d548603f9d124e8b83e94fc64a6

Since @toga4’s report spans multiple databases, it’s very likely related. However, my report seems to be an issue that occurs within a single transaction. In fact, I can still reproduce the problem with the same steps on v1.5.50.

It seems there are still unresolved issues with read/write multiplexed sessions.

**Comment by sakthivelmanii** [comment]
@apstndb can you please a give a Go script to reproduce this issue?

**Comment by apstndb** [comment]
@sakthivelmanii

The issue I reported in https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/282#issuecomment-3659846637 is still reproducible on emulator **v1.5.50** (which claims to have fixed this issue). The root cause appears to be different from the cross-database `TransactionID` collision that was fixed in v1.5.50.

**Reproduction repository:** https://github.com/apstndb/spanner-emulator-mux-session-repro

### Environment

- Emulator: **v1.5.50** (also reproduced on latest)
- Go client: **cloud.google.com/go/spanner v1.87.0** (multiplexed sessions for RW enabled by default, controllable via `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW`)

### Reproduction conditions

The bug reproduces when **all three** of the following conditions are met:

1. **Multiplexed sessions for RW** are enabled
2. The transaction uses **explicit `BeginTransaction` RPC** (not inlined with the first statement)
3. The commit contains **mutations** (DML-only commits are not affected)

Note: I have not tested whether mutations are also lost when DML and mutations coexist in the same explicit-begin transaction.

This explains why my original report (using [spanner-mycli](https://github.com/apstndb/spanner-mycli)) was affected: `spanner-mycli` uses `NewReadWriteStmtBasedTransaction`, which defaults to explicit `BeginTransaction`. When a user runs a mutation-only command (e.g., `MUTATE ... DELETE`), this path is taken.

### Test matrix

Full results: [run_all_output.txt](https://github.com/apstndb/spanner-emulator-mux-session-repro/blob/main/run_all_output.txt)

BUG cases only (all with `MULTIPLEXED_SESSIONS_FOR_RW` enabled):

| DELETE method | `BeginTransactionOption` | Result |
|---|---|---|
| `StmtBasedTransaction` + `BufferWrite` | default (= explicit) | **BUG** |
| `StmtBasedTransaction` + `BufferWrite` | explicit | **BUG** |
| `StmtBasedTransaction` + `BufferWrite` | inlined | PASS |
| `ReadWriteTransaction` + `BufferWrite` | default (= inlined) | PASS |
| `ReadWriteTransaction` + `BufferWrite` | explicit | **BUG** |
| `ReadWriteTransaction` + `BufferWrite` | inlined | PASS |
| `client.Apply` | (inlined internally) | PASS |
| DML (any begin mode) | any | PASS |

### Key observations

- The **INSERT method does not matter**; only the DELETE (mutation commit) triggers the bug.
- `client.Apply` works correctly because it uses inlined `BeginTransaction` internally.
- DML-only transactions work regardless of begin mode.
- Setting `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW=false` works around the issue entirely.

This suggests the emulator's multiplexed session transaction manager does not correctly handle mutations committed in a transaction that was started via an explicit `BeginTransaction` RPC.

**Comment by apstndb** [comment]
Additionally confirmed that this is not specific to DELETE mutations — **INSERT mutations are also silently lost** under the same conditions.

```go
// INSERT via mutation + explicit BeginTransaction on multiplexed session.
txn, _ := spanner.NewReadWriteStmtBasedTransactionWithOptions(ctx, client,
    spanner.TransactionOptions{BeginTransactionOption: spanner.ExplicitBeginTransaction})
txn.BufferWrite([]*spanner.Mutation{
    spanner.InsertOrUpdate("T", []string{"PK", "Val"}, []interface{}{int64(1), int64(1)}),
})
txn.CommitWithReturnResp(ctx) // succeeds without error

// But the row does not exist.
_, err := client.Single().ReadRow(ctx, "T", spanner.Key{int64(1)}, []string{"PK"})
// err: codes.NotFound
```

| `BeginTransactionOption` | INSERT mutation result |
|---|---|
| default (= explicit for StmtBased) | **BUG** (row not found) |
| inlined | PASS (row exists) |
| explicit | **BUG** (row not found) |

All mutations committed via explicit `BeginTransaction` on a multiplexed session are silently discarded, regardless of mutation type.

**Comment by sakthivelmanii** [comment]
@apstndb we will fix this issue in our next emulator release. Is there any specific reason why you are trying to do a explicit begin in this case for mutations-only case?

**Comment by apstndb** [comment]
spanner-mycli is a fork of spanner-cli, and we introduced `spanner.ReadWriteStmtBasedTransaction` to simplify implementing the common `BEGIN [TRANSACTION]; ...; COMMIT [TRANSACTION]` workflow, in line with the direction taken in spanner-cli. For example, https://github.com/cloudspannerecosystem/spanner-cli/pull/84 refactored spanner-cli’s read-write transaction implementation to use `spanner.ReadWriteStmtBasedTransaction`, which (1) simplified the transaction logic and (2) made it possible to surface more detailed server-side errors (e.g., aborted errors) by hooking error responses from both DML execution and Commit.

In spanner-mycli, even in its `MUTATE` implementation, I intentionally follow the same design/behavior as spanner-cli. Since reducing round trips in an interactive client is not a major concern for me, rather than branching between `txn.BufferWrite` for explicit transactions and `client.Apply` for implicit (AUTOCOMMIT-like) transactions, I wanted to unify the behavior and always use `txn.BufferWrite`.
