### ISSUE TITLE
Support all documented query hints

### ISSUE THREAD

**Issue by apstndb** [GoogleCloudPlatform/cloud-spanner-emulator#300]
This emulator validates names and values of query hints.
It is useful to ensure that the query is valid, but sometimes, valid queries can be rejected because of unimplemented hints.

Ideally, all valid queries should be accepted.

[Statement Hints](https://docs.cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#statement_hints)

|hint name| supported|
|---|---|
|`USE_ADDITIONAL_PARALLELISM`|Yes|
|`OPTIMIZER_VERSION`|No|
|`OPTIMIZER_STATISTICS_PACKAGE`|No|
|`ALLOW_DISTRIBUTED_MERGE`|No|
|`LOCK_SCANNED_RANGES	`|Yes|
|`SCAN_METHOD`|Yes, but `AUTO` is rejected|
|`EXECUTION_METHOD`|No|
|`USE_UNENFORCED_FOREIGN_KEY`|No|
|`ALLOW_TIMESTAMP_PREDICATE_PUSHDOWN`|No|

```
spanner> @{OPTIMIZER_VERSION=latest} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: OPTIMIZER_VERSION.
spanner> @{OPTIMIZER_STATISTICS_PACKAGE=latest} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: OPTIMIZER_STATISTICS_PACKAGE.
spanner> @{ALLOW_DISTRIBUTED_MERGE=TRUE} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: ALLOW_DISTRIBUTED_MERGE.
spanner> @{SCAN_METHOD=AUTO} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Invalid hint value for: SCAN_METHOD hint: "AUTO".
spanner> @{EXECUTION_METHOD=BATCH} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: EXECUTION_METHOD.
spanner> @{USE_UNENFORCED_FOREIGN_KEY=TRUE} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: USE_UNENFORCED_FOREIGN_KEY.
spanner> @{ALLOW_TIMESTAMP_PREDICATE_PUSHDOWN=TRUE} SELECT 1;
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: ALLOW_TIMESTAMP_PREDICATE_PUSHDOWN.
```

[Table hints](https://docs.cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#table_hints)

|hint name| supported|
|---|---|
|`FORCE_INDEX`|Yes|
|`GROUPBY_SCAN_OPTIMIZATION`|Yes|
|`SCAN_METHOD`|Yes|
|`INDEX_STRATEGY`|Yes|
|`SEEKABLE_KEY_SIZE`|No|

```
spanner> SELECT * FROM Singers@{FORCE_INDEX=SingersByFirstLastName,SEEKABLE_KEY_SIZE=1};
ERROR: spanner: code="InvalidArgument", desc: Unsupported hint: SEEKABLE_KEY_SIZE.
```

**Comment by sp11623** [comment]
This is fixed by [v1.5.53](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.53) release. Can you please verify? Thanks!

**Comment by apstndb** [comment]
@sp11623
I confirmed that nothing has changed.
I think that
“Add support for filter column in information_schema.indexes” (Issue #300)
is not related to this issue.

**Comment by apstndb** [comment]
I believe this issue should be reopened.

**Comment by olegkoskin** [comment]
+1 
It's 2026, but Spanner Emulator still doesn't support `OPTIMIZER_VERSION` hint.
I get an error:
`Caused by: com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unsupported hint: OPTIMIZER_VERSION.`

**Comment by KaguraGateway** [comment]
I noticed that the `scan_method` table hint is listed as supported in this issue, but the value `columnar` is not accepted — the emulator rejects it with an error, while production Spanner handles it gracefully.

Emulator version: v1.5.54
Error: `Invalid hint value for: scan_method hint: "columnar".`

For additional context: `columnar_policy` DDL support was added in v1.5.52 (`ALTER TABLE ... SET OPTIONS (columnar_policy = 'enabled')` is accepted), but the corresponding query hint `@{scan_method=columnar}` is rejected at query time.
On production Spanner, the hint is silently ignored when `columnar_policy` is not enabled on the target table.
